name: deploy dev branch
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: [self-hosted,arbor_demo]
    steps:
      - uses: actions/checkout@v4
      - name: created .env.dev file from secrets
        run: printf "%s" "${{ secrets.ENV_DEV_FILE }}" > .env.dev

      - name: build docker image
        run: |
          docker build \
            --build-arg ENV_FILE=.env.dev \
            -t my-app-dev:latest .
