name: deploy dev branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted,arbor_demo]
    steps:
      - uses: actions/checkout@v4

      - name: created .env.dev file from secrets
        run: |
          cat <<EOF > .env.main
          ${{ secrets.ENV_MAIN_FILE }}
          EOF

      - name: build docker image
        run: |
          docker build \
            --build-arg ENV_FILE=.env.main \
            -t my-app-main:latest .
